apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp-ui
  template:
    metadata:
      labels:
        app: reactapp-ui
    spec:
      containers:
      - name: reactapp-ui
        image: kokismoki/reactapp-ui:30fdcd07ffd3e957d2f65bc8ac4badd35f077c36
        ports:
        - containerPort: 80
